controllers:
    resource:
        path: ../../src/Controller/
        namespace: App\Controller
    type: attribute

api:
    resource:
        path: ../../src/Repository/
        namespace: App\Repository
    type: attribute

kernel:
    resource: App\Kernel
    type: attribute
